name: "Uclub Auto Signin"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: "46 22,11 * * *"

env:
  TZ: Asia/Shanghai
  USERS: ${{secrets.USERS}}
  TELEGRAMBOT_TOKEN: ${{ secrets.TELEGRAMBOT_TOKEN }}
  TELEGRAMBOT_CHATID: ${{ secrets.TELEGRAMBOT_CHATID }}
  PUSH_KEY: ${{secrets.PUSH_KEY}}
  QMSG_KEY: ${{ secrets.QMSG_KEY }}

jobs:
  auto_signin:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2

      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip           
          python -m pip install --upgrade schedule
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt; 
          fi
      - name: "Signin"
        run: |
          date
          users_array = ($(echo ${USERS} | tr ';' ' '))

          if [ "${users_array}" ]; then
              user_count = 1
              for user in ${users_array[@]}; do
                  username = $(echo ${user} | awk -F'----' '{print $1}')
                  passwd = $(echo ${user} | awk -F'----' '{print $2}')

                  if [ -z "${username}" ] || [ -z "${passwd}" ]; then
                      echo "账号信息配置异常，请检查配置" && exit 1
                  fi

                  info = "## 正在签到第 " + ${user_count}" + "个用户: "
                  echo $info
                  python3 main.py <<-EOF
          ${username}
          ${passwd}
          EOF
                  user_count=$(expr ${user_count} + 1)
                  sleep 66
              done
          else
              echo "用户组环境变量未配置" && exit 1
          fi
